#ifndef CONFIG_H
#define CONFIG_H

// AUDIO CONSTANTS //
#define SAMPLE_RATE 48000
#define FRAMES_PER_BUFFER 1024
#define WAVETABLE_SIZE 16384

// COUNT CONSTANTS //
#define PARTIAL_COUNT 3
#define LFO_COUNT 2
#define WAVETABLE_COUNT 4
#define TEXTBOX_COUNT 3
#define CONTROL_COUNT 3
#define MAX_TEXT_LENGTH 6

// VISUAL DRAW CONSTANTS //
#define PARTIAL_DRAW_INCREMENT 0.10
#define PARTIAL_PHASE_INCREMENT 0.10
#define ADDITIVE_DRAW_INCREMENT 0.10
#define WAVETABLE_DRAW_INCREMENT 0.10

// VISUAL WAVE PARAMETERS CONSTANTS //
#define WAVE_HEIGHT_SCALE -30

// WAVE TYPE CONSTANTS //
#define SINE 0
#define SQUARE 1
#define SAW 2
#define TRIANGLE 3

// CONTROL TYPE CONSTANTS //
#define VOLUME_CONTROL 0
#define WOBBLE_CONTROL 1
#define TREMOLO_CONTROL 2

// LFO TYPE CONSTANTS
#define WOBBLE 0
#define TREMOLO 1

// LFO PARAMETER CONSTANTS
#define LFO_AMP 50

// KNOB PARAMETERS
#define KNOB_WIDTH 10
#define KNOB_HEIGHT 10

#endif
